services:
  api:
    build:
      context: ./BookShop
    ports:
      - "13779:13779"
    volumes:
      - ./BookShop/wwwroot:/app/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__WebAppUrl=http://localhost:13779
